# -*- coding: utf-8 -*-
"""Leckja_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10QX75NJXJkXyJKQqvsg8D0qxRPxY3eFM

#Lekcja 3
##listy

##tworzenie listy
"""

pustalista = []
pustalista2 = list()
print(pustalista ,pustalista2)
kolory = ["red", "blue", "green", "orange"]
print(kolory)
print(kolory[0])
print(kolory[:])
print(kolory[1:4])
print(kolory[0:3:2])

"""#dodwanie elementow do listy"""

kolory[len(kolory):] =["yellow"]
print(kolory)
kolory.append('blacksorrow')
print(kolory)
kolory.insert(2, 'blacksorrow')
print(kolory)

"""##sprawdzanie czy element jest czty nie"""

print("liczba wystapien 'black':", kolory.count('blacksorrow'))
print('czy "pink" jest w liscie kolorow?:', "pink" in kolory)
print('czy nie ma "black"   liscie kolorow?:', "black" not in kolory)

"""##usuwanie elementow z list"""

liczby=[4,5,6]
print(liczby)
liczby.remove(5)
print(liczby)
liczby=[4,5,6]
liczby.pop(2)
print(liczby)

"""##odwrocona lista"""

liczby=[1,2,3]
liczby.reverse
print(liczby)

kolory = ['red', 'blue', 'black']
liczby=[1,2,5]
listamieszana=kolory+liczby
print(listamieszana)
listamieszana1=list(liczby)
listamieszana1.append(liczby)
print(listamieszana1)
listamieszana2=[]
listamieszana2.append(kolory)
listamieszana2.append(liczby)
print(listamieszana2)

"""##sortowanie"""

liczby=[5,2,6,8,2,1]
liczby.sort()
print(liczby)
print("dlugosc przez czysczeniem", len(liczby))
liczby.clear()
print(liczby)

"""#zadania

1.utworz liste uczniow (imiona)

2.dodaj nowy element do listy ('stanislaw')

3.usunmy z listy pierwszy element o nazwie ('ania")

4.usun element o indeksie 3

5.utworz liste samochody

6.polacz je

7.posortuj

8.usunliste
"""

ludzie=['ivan', 'till', 'mizi', 'sua', 'ania', 'luka', 'hyuna']
print(ludzie)

ludzie.append('stanislaw')
print(ludzie)

ludzie.remove('ania')
print(ludzie)

ludzie.pop(3)
print(ludzie)

samochody=["pojazdjezdzacy","jezdzik", "wyscigowka"]

listajakastam=samochody+ludzie
print(listajakastam)

listajakastam.sort()
print(listajakastam)

listajakastam.pop(2)
listajakastam.pop(3)
listajakastam.pop(4)
print(listajakastam)

listajakastam.clear()
print(listajakastam)

"""## wycinanie elementow z listy

"""

nums=list(range(5))
print(nums)
print(nums[0:3])
print(nums[2:])
print(nums[:])
print(nums[:-1])
nums[2:4] = [8,9]
print(nums)

"""##zbiory (sets)"""

kolory1={'black', 'blue', 'red', 'grey'}
kolory2={'grey', 'purple', 'black', 'blue'}
allcolors=kolory1|kolory2
print(allcolors)

pustyzbior=set()
print(pustyzbior)
kolory3={'yellow', 'pink'}
print(kolory3)
wszystkiekolory=set(kolory1) | set(kolory2) | set(kolory3)
print(wszystkiekolory)
wszystkiekolory.add('violet')
print(wszystkiekolory)
wszystkiekolory.discard('yellow')
print(wszystkiekolory)
wszystkiekolory=list(wszystkiekolory)
print(wszystkiekolory)

##czy zbiory sie w sobie zawieraja

print("czy kolory1 zawiera w calosci kolory2?", set(kolory1) > set(kolory2))
print("czy kolory1 zawiera w calosci zbior {black,blue}?" ,  set(kolory1) > set(['black','blue']))

wspolnekolory= set(kolory1) & set(kolory2)
print(wspolnekolory)
niewspolnekolory = set(kolory1) ^ set(kolory2)
print(niewspolnekolory)

animals = {'cat', 'dog'}
print('cat' in animals)
print('fish' in animals)

animals.add('fish')
print('fish' in animals)
print(len(animals))

animals.add('cat')
print(animals)
print(len(animals))
animals.remove('cat')
print(len(animals))

"""##krotki (tuples)"""

tuple1=(5, 10, 15, "hurray!")
print(tuple1)
print(tuple1[1])
print(tuple1[3])

tuple[1]=5

"""##slowniki (dictionaries)

"""

pustyslownik={}
pustyslownik2=dict()
print(pustyslownik, pustyslownik2)
autor={
       'imie': "maciej",
       "nazwisko": "wilamowski",
       "wiek": 32
       }
print(autor)
autor["wzrost"] = 192
print(autor)
autor[1] = "python"
print(autor)
del autor["wiek"]
print(autor)

wiekautora= {"wiek" :99}
autor.update(wiekautora)
print(autor)
autor.update({'adres' : 'klonowa'})
print(autor)

print(set(autor.keys()))

print(autor.items())

d = {'cat' : 'cute', 'dog' : 'furry'}
print(d['cat'])
print('dog' in d)

d['fish'] ='wet'
print(d['fish'])
print(d)

print(d['monkey'])