# -*- coding: utf-8 -*-
"""lekcja_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/nickowca/7d36991865fb14133b2745fc92360bc3/lekcja_1.ipynb

# Lekcja 1 - wprowadzanie do **Colaba**

1.   Zapozanie z dzialaniem programu
2.   Funkcja `print`
3.   Przykladowe wykorzystanie funkcji `print`

```
print("Thank  you for being the victim of my shallow emotions")
print('Mam na imie Ivan')
```
>opis dzialania czesci kodu
"""

print('Thank  you for being the victim of my shallow emotions')

print('Mam na imie Ivan')

x=8970

print(x)

"""## Przyklad 1"""

wiek = 22
x=1; y=2
print('mam', wiek, 'lata')
print(f'mam  {wiek} lata')
wiek = '12 lat'
print(wiek)

"""## Przykald 2"""

print('pierwsza linia\n\ndruga linia\ntrzecia')

"""## Przyklad 3"""

print('cudzyslow: \'python\'')
print('tabulator: \tpo spacji')

"""## Przyklad 4"""

imie = "anna"
wiek = 19
print(imie, "ma", wiek, "lat")
print(f'Nazywa sie {imie} i ma {wiek} lat')

"""## Przyklad 5"""

print(imie)
imie = "kasia"
print('czesc, mam na imie ' + imie + "!")

"""## przyklad 6"""

print("2025", "09", "02", sep=".")

"""## Przyklad 7"""

print("ala ma kota", end=" :3 ")
print("a kot ma ale")

"""##Zad 1
napisz swoje imie konczac linie "dupa"

"""

print("Alexander", end=" dupa ")
print("Żychowski")

"""##Zad 2"""

print("Alexander")
print("Żychowski")

"""##Zad 3"""

x = "jedliczu"
print(f"mieszkam w {x}")

"""##Zad 4"""

imie = "Alexander"
wiek = "16"
print(f"nazywam sie {imie} i mam {wiek} lat")

"""##Zad 5"""

print("14", "02", "2025", sep="/")

"""##Zad 6
operator * #
"""

print(6 *"#")

"""#Zadania Trudniejsze
##Zad 1
"""

for i in range(0, 11):
  print(i, "x 7 =", i * 7)

"""##Zad 2"""

imie = "Ivan"
print("*" * (len(imie) + 4))
print("* " + imie + " *")
print("*" * (len(imie) + 4))

"""#Testy w domu"""

for i in range(0,16):
  print(f"{i} x 5 = {i*5}")

imie="toya"
print("x"* (len(imie)+4))
print("x "+imie+" x")
print("x"* (len(imie)+4))