# -*- coding: utf-8 -*-
"""Lekcja_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R-q7VDI2ELMcMTSXzgNVyKkNayvN5k9V

#Lekcja 2 - Zmienne i typy Danych
int, float, str, bool

##Przyklad 1
"""

e = 2.23
r = 4
pi = "3.14"
text = "witaj swiecie"
print("typ zmiennej e to:", type(e), e)
print("typ zmiennej r to:", type(r), r)
print("typ zmiennej text: ", type(text),pi)
print("typ zmiennej pi to: ", type(pi), text)

"""##Przyklad 2"""

print("Typ zmiennej e to: %s, a zmiennej text: %s, a zmiennej pi to: %s" % (type(e),
      type(text), type(pi)))

"""##przyklad 3"""

print(str(e) + pi)
print(e + float(pi))
print(int(float(pi)))

"""##przyklad 4"""

a = 10
b = 3.5
tekst = "meow"
prawda = True
print(a)
print(b)
print(tekst)
print(type(prawda))

"""##przyklad 5"""

print(type(10))
print(type(3.14))
print(type("Ala"))
print(type(True))

"""##Przyklad 6
int jest caly bez . a float moze byc 89.70 a int  byloby 89
"""

x = 3
print(x, type(x))

x = 3
print(x + 1)
print(x - 1)
print(x * 2)
print(x ** 2)
y = 3.5
print(int(x+y)) #to normalnie jest float ale int robi ze jest int
print(y/2)
print(y//2)      #dzielenie bez reszty
print(y % 2)     #reszta z dzielenia

"""## Przyklad 7"""

x += 1    #x = x+1
print(x)
x *= 2  #x = x**2
print(x)

"""## przyklad 8"""

t, f = True, False
print(type(t))

"""## przyklad 9"""

t, f = True, False
print(t and f)
print(f or t)
print(not t)
print(t != f)

"""# strings"""

hello_w = "hello"
world_w = "world"
print(hello_w, len(world_w))

hello_w = "hello"
world_w = "world"
hw = hello_w + " " + world_w + " 01"
print(hw)

s = "hello"
print(s.capitalize())
print(s.upper())
print(s.rjust(7))
print(s.center(7))
print(s.replace('l', ' uwu '))
print('  world '.strip())

"""# Containers

## Listy

Lista jest odpowiednikiem tablicy w Pythonie
"""

# listy tworzymy z wykorzystaniem  nawiasow kwadratowych
pustaLista = []
# mozemy tez stworzyc liste tworzac nowy obiekt, ktory jest lista
pustalista2 = list()
print(pustaLista)
print(pustalista2)
kolory = ["red", "blue", "green", "black", "white"]
print(kolory)
print(kolory[0])
print(kolory[:])
print(kolory[2])
print(kolory[-1])
print(kolory[-2])
print(kolory[2:4])
print(kolory[0:3:2])

uwu = input()
print("lubisz w ", uwu)