# -*- coding: utf-8 -*-
"""Lekcja_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16YgSIXFntncxkWweLt62at6FfPXOcGZ_

#lekcja 4 - wejscie danych i instrukcje warunkowe

##pobieranie takstu od uzytkownika
"""

imie  = input()
print("witaj,", imie)

"""##pobieranie liczby od uzykownika"""

wiek = int(input("ile masz lat? "))
print("za rok bedziesz miec", wiek + 1, "lat")

"""##prosty warunek If"""

wiek = int(input("podaj swoj wiek: "))
if wiek >=18:
  print("jestes pelnoletni")

"""##if z else"""

wiek = int(input("podaj swoj wiek: "))
if wiek >=19:
  print("jestes pelnoletni.")
else:
  print("nie jestes pelnoletn.")

"""##instrukcje wielowarunkowe if elif else
and or not
"""

ocena = int(input("podaj ocene (1-6): "))
if ocena == 1 or ocena ==2:
  print("slabo")
elif ocena == 3 or ocena ==4:
  print("dobrze")
elif ocena == 5 or ocena ==6:
  print("super")
else:
  print("nie ma takiej opcji")

wiek = int(input("podaj wiek: "))
if wiek >= 16 and wiek <65:
  print("jestes w wieku produkcyjnym")
else:
  print("jestes poza wiekiem produkcyjnym")

liczba = int(input("podaj liczbe: "))
if liczba % 2 ==0:
  print("liczba jest parzysta")
else:
  print("liczba nie jest parzytsa")

"""##sprawdzanie wielu waronkow jedncozesnie"""

haslo = input("podaj haslo: ")
if len(haslo) >= 8 and "@" in haslo:
  print("haslo mocne")
else:
  print("slabe")

"""##rok przestepny"""

rok = int(input("podaj rok: "))
if rok % 4 and rok % 100 != 0:
  print("rok jest przestepny")
else:
   print("nie przestepny")

"""##funkcja kwadratowa"""

import math
x = math.sqrt(25)
print(x)

y = int(pow(x,2))
print(y)

"""1. pobierz z klawiatury parametry a b c
2. oblicz delte b^2-4ac
3. jezeli delta >0

rownaie ma 2 roziwacania
x1
"""

import math
a, b, c = input("podaj a b c ").split( )
a = int(a)
b = int(b)
c = int(c)
delta = pow(b,2) - 4*a*c
if delta > 0:
  print("rowananie ma 2 rozwiacania")
  x1 = (-b - math.sqrt(delta)) / (2*a)
  x2 = (-b + math.sqrt(delta)) / (2*a)
  print("x1 =", x1)
  print("x2 =", x2)
elif delta == 0:
  print("rownanie ma jedno roziwanaie")
  x = -b / (2*a)
  print("x =", x)
else:
  print("rowannie nie ma rozwiazan")

"""##instrukcje warunkowe zagniezdzorne 🥰"""

import math
x = int(input('podaj liczbe: '))
if x > 0:
  if x % 2 == 0:
    print("liczba dodatnia i pazrysta")
  else:
    print("liczba dodatnia i nieparzysta")
elif x < 0:
  if x %2 == 0:
    print("liczba ujemna parzysta")
  else:
    print("liczba ujemna i nieparzysta")
else:
  print("liczba to zero")

print("masz do pokonania trzy rozwidzlenia drog")
print("przed kazdym z nim musisz wyrbac odpowiedznia droge")
d = int(input("wybierz droge (1), (2) lub (3):  "))

import random
liczba = random.randint(1,3)
if d == liczba:
  print("omg sigma")
  d = int(input("wybierz droge 1 2 lub 3 "))
  liczba = random.randint(1,3)
  if d == liczba:
   print("omg sigma")
   d = int(input("wybierz droge 1 2 lub 3 "))
   liczba = random.randint(1,3)
   if d == liczba:
    print("omg sigma")
   else:
        print("loser")
        print("wylosowana liczba byla:", liczba)


  else:
       print("loser")
       print("wylosowana liczba byla:", liczba)
else:
  print("loser")
  print("wylosowana liczba byla:", liczba)

temp =int(input("podaj temperature "))
wilgotnosc = int(input("podaj wilgotnosc powietrza "))
if temp <20:
  if wilgotnosc >70:
    print("wez parasol i kurtke!")
  else:
    print("wez tylko kurtke")
else:
  if wilgotnosc > 70:
    print("wez parasol")
  else:
    print("pogoda jest idealna")

temp = 15
wilgotnosc = 80
if temp < 20 and wilgotnosc >70:
  print("wez parasol i kurtke")
elif temp < 20 and wilgotnosc >70:
  print("wez tylko kurtke")
elif temp >= 20 and wilgotnosc >70:
  print("weze tylko parasol")
else:
  print("nic nie bierz")

"""to chyba nikodema"""

import math

"""
wyliczanie rozwiazan funkcji kwadratowej
"""


def funkcja_kwadratowa():
    a = int(input("parametr a: "))
    b = int(input("parametr b: "))
    c = int(input("parametr c: "))

    delta = (b ** 2) - (4 * (a * c))

    if delta > 0:
        x1 = (- b - math.sqrt(delta)) / (2*a)
        x2 = (- b + math.sqrt(delta)) / (2 * a)
        print("mozliwe rozwiazania: \n x = ", x1, "\n x = ", x2)
    elif delta == 0:
        x = (-b) / (2*a)
        print(x)
    else:
        print("rownanie nie ma rozwiazania")


"""
instrukcja zagnizdzona
"""

def instrukcja_zagniezdzona():
    x = int(input("podaj liczbe: "))
    if x > 0:
        if x % 2 == 0:
            print("liczba dodatnia i parzysta")
        else:
            print("liczba dodatnia i nieparzysta")
    elif x < 0:
        if x % 2 == 0:
            print("liczba ujemna i parzysta")
        else:
            print("liczba ujemna i nieparzysta")
    else:
        print("x = 0")

"""
prosty kalkulator w pythonie
"""


def kalkualtor():

    def addition():
        a = int(input("first num: "))
        b = int(input("second num: "))
        print(f"{a} + {b} = {a + b}")

    def subtraction():
        a = int(input("first num: "))
        b = int(input("second num: "))
        print(f"{a} - {b} = {a - b}")

    def multiplication():
        a = int(input("first num: "))
        b = int(input("second num: "))
        print(f"{a} x {b} = {a * b}")

    def division():
        a = int(input("first num: "))
        b = int(input("second num: "))
        print(f"{a} / {b} = {a / b}")

    def end():
        print("see you later")
        return

    while True:
        choice = input("what would you like to do? \n [1- add, 2 - subtract, 3 - multiply or 4 - divide two numbers]: ")
        if choice == '1':
            addition()
        elif choice == '2':
            subtraction()
        elif choice == '3':
            multiplication()
        elif choice == '4':
            division()
        elif choice == '5':
            end()

        nextcalc = input("run program again? ")
        if nextcalc == "no":
            break
    else:
        print("invalid input")


def labirynt():
    import random
    wins = 0
    print('masz do pokonania trzy rozwidlenia dróg')
    print('przed kazdym z nich musisz wybrac odpowiednia droge')
    print('jesli zle wybierzesz droge na pewnym etapie to przegrywasz')

    ver = int(input("chcesz zagrac w 0 - latwiejsza wersje czy 1 - trudniejsza wersje? "))
    if ver == 0:
        while wins < 3:
            d = int(input("wybierz droge lewo (1) prawo (2) prosto (3): "))

            liczba = random.sample(range(1,4), 2)
            if d == liczba:
                print("Dobrze trafiłeś, przechodzisz dalej")
                wins += 1
            else:
                print("wpadles w przepasc, poprawna odpowiedz to byla: ", liczba)
                break
        if wins == 3:
            print("Gratulacje! Przeszedłeś przez labirynt!")
    elif ver == 1:
        while wins < 3:
            d = int(input("wybierz droge lewo (1) prawo (2) prosto (3): "))

            liczba = random.randint(1, 3)
            if d == liczba:
                print("Dobrze trafiłeś, przechodzisz dalej")
                wins += 1
            else:
                print("wpadles w przepasc, poprawna odpowiedz to byla: ", liczba)
                break
        if wins == 3:
            print("Gratulacje! Przeszedłeś przez labirynt!")


def temperatura():

    temp = int(input("wprowadz temperature: "))
    humid = int(input("wprowadz wilgotnosc: "))

    if temp < 20 and humid > 70:
        print("weź parasol i kurtke")
    elif temp < 20:
        print("wez tylko kurtke")
    elif humid > 70:
        print("wez parasol")
    else:
        print("pogoda jest idealna idz dotknij trawy w koncu")