# -*- coding: utf-8 -*-
"""Zadania_z_lekcji.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Me1WzgG7rU7hfJeJ-bIq6kY7O8S3t-bb

Utworz liste uczniow

dodaj losowy nowy element

usun 3 element z listy

usun anie

utworz liste o swoich mezczyznach

polacz je w jedna

posortuj je

usun cala liste
"""

uczniowie=["marcin", "cipolot", "nwm", "sraktyn","kochambladea", "ania"]
print(uczniowie)
uczniowie.append("kupa")
print(uczniowie)
uczniowie.remove("ania")
print(uczniowie)
mymen=["Blade", "DanHeng", "Ivan", "till"]
listafajna=mymen+uczniowie
print(listafajna)
listafajna.sort()
print(listafajna)
listafajna.clear()
print(listafajna)

"""utworz 3 zbiory o roznych kolorach kolory1 /2 /3

polacz je w jenda

dodaj nowy kolor i odejmij jeden ze zbioru

sprawdz czy zbior zawiera caly zbior kolory1

sprawdz czy zawiera 2 wybrane kolory

jakie sa wspolne kolory w zbiorach 2  i 1

nie wspolne

sprawdz czy jest jakis kolor w tym




"""

set1={"red","blue","black"}
set2={"orange","yellow","b"}
set3={"green","purple","pink"}
kolory=set1|set2|set3
print(kolory)
kolory.add("cyan")
kolory.remove("purple")
print(kolory)
print("czy zbior 1 zawiera zbior 2?", set(set1) > set(set2))
print("czy zbior 1 zawiera czerwony i niebieski?", set(set1) > set(["red" , "blue"]))
wspolnekolory=set(set1) & set(set2)
print(wspolnekolory)
niewspolnekolory=set(set1) ^ set(set2)
print(niewspolnekolory)
print("czy w zbiorze 1 jest kolor zielony?", {"green"} in set1)

"""utworz slownik ze jakimis swoimi infroamcjami wiek imie nazwisko

dodaj wzrost

usun wiek

dodaj zmienna losowa i podpisz pod nia wiek nastepnie dodaj go poprzez zmeinna

dodaj feetsize poprzez .update
"""

dictionary1={"name":"Blade","surname":"unknown","age":"old"}
print(dictionary1)
dictionary1["height"]=189
print(dictionary1)
del dictionary1["age"]
print(dictionary1)
uwuwiek={"age":"600+"}
dictionary1.update(uwuwiek)
print(dictionary1)
dictionary1.update({"feetsize":"stupka"})
print(dictionary1)
print(set(dictionary1.keys()))
print(set(dictionary1.items()))

"""nie umeim"""

import math
x=int(input("podaj liczbe "))
if x > 0:
  if x % 2 ==0 :
   print("liczba jest dodatnia i parzysta")
  else:
   print("liczba jest dodatnia i nieparzysta")
elif x < 0:
   if x % 2 ==0 :
     print("liczba jest ujemna i parzysta")
   else:
     print("liczba jest ujemna i nieparzysta")
else:
    print("liczba jest zero")