# -*- coding: utf-8 -*-
"""zadania leckja 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjLQR2j3HKKsQNIu5nElXw4Ag0SwrwL2
"""

uczniowie = ["anna", "jakub", "mateusz", "patryk"]
print(uczniowie)
uczniowie.append("stanislaw")
print(uczniowie)
uczniowie.remove("anna")
print(uczniowie)
uczniowie.pop(3)
print(uczniowie)

samochody = ["bmw", "mercedes", "audi"]
join = uczniowie + samochody
join.sort()
print(join)
join[2:4] = []
print(join)
# join.clear()
# print(join)
print(join[-1])



kolory1=['black', 'blue', 'red', 'grey']
kolory2=['grey', 'purple', 'black', 'blue']
pustyzbior=set()
print(pustyzbior)
kolory3=['yellow', 'pink']
print(kolory3)
wszystkiekolory=set(kolory1) | set(kolory2) | set(kolory3)
print(wszystkiekolory)
wszystkiekolory.add('violet')
print(wszystkiekolory)
wszystkiekolory.discard('yellow')
print(wszystkiekolory)
wszystkiekolory=list(wszystkiekolory)
print(wszystkiekolory)

print("czy kolory1 zawiera w calosci kolory2?", set(kolory1) > set(kolory2))
print("czy kolory1 zawiera w calosci zbior ['black', 'blue']?", set(kolory1) > set(['black','blue']))
print(kolory1)

animals = {'cat', 'dog'}
print('cat' in animals)
print('fish' in animals)
animals.add('fish')
print('fish' in animals)
print(len(animals))
animals.add('cat')
print(len(animals))
animals.remove('cat')
print(len(animals))
print(animals)

tuple1 = (5, 10, 15, "hurray!")
print(tuple1)
print(tuple1[2])
print(tuple1[3])

pustyslownik={}
pustyslownik2=dict()
print(pustyslownik, pustyslownik2)
autor={'imie': "maciej", "nazwisko": "wilamowski", }
print(autor)
autor["wzrost"] = 192
print(autor)
del autor["wzrost"]
print(autor)
autor[1] = "srajton"
print(autor)
print(autor.keys())
print(autor.values())
print(autor.items())
wiekautora = {"wiek": 27}
autor.update(wiekautora)
print(autor)
autor.update({'adres':'klonowa'})
print(autor)

wiek = int(input("podaj swoj wiek: "))
if wiek >=18:
  print("jutro umrzesz.")
else:
  print("nie jestes pelnoletn.")

x = int(input("podaj liczbe: "))
if x % 2 == 0:
  print("liczba jest parzysta.")
else:
  print("liczba jest nieparzysta.")

import math

"""
wyliczanie rozwiazan funkcji kwadratowej
"""


def funkcja_kwadratowa():
    a = int(input("parametr a: "))
    b = int(input("parametr b: "))
    c = int(input("parametr c: "))

    delta = (b ** 2) - (4 * (a * c))

    if delta > 0:
        x1 = (- b - math.sqrt(delta)) / (2*a)
        x2 = (- b + math.sqrt(delta)) / (2 * a)
        print("mozliwe rozwiazania: \n x = ", x1, "\n x = ", x2)
    elif delta == 0:
        x = (-b) / (2*a)
        print(x)
    else:
        print("rownanie nie ma rozwiazania")

funkcja_kwadratowa()