# -*- coding: utf-8 -*-
"""Lekcja_9 - Biblioteka JSON_dla_uczniów.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jYFjvuCa8u1MCwj4LK3mbiTRl24Sxe_v

##Lekcja 9 - Wprowadzenie do biblioteki `json` w Pythonie

### 1. Co to jest format JSON i jego zastosowanie?

JSON czytamy „dżej-son”. To skrót od **JavaScript Object Notation**.

Wbrew nazwie nie jest to format związany tylko z JavaScriptem — jest używany **wszędzie**:
* w aplikacjach mobilnych,
* na stronach internetowych,
* w grach,
* w serwisach takich jak Google Maps, OpenWeather, YouTube,
* do przechowywania konfiguracji programów,
* do zapisu danych aplikacji.

**JSON jest dziś najpopularniejszym formatem wymiany danych**

**Dlaczego?**

* jest lekki, szybki i prosty,
* jest czytelny dla ludzi,
* każdy język programowania potrafi z nim pracować,
* znakomicie nadaje się do przechowywania danych w plikach.

###Przykład struktury JSON
```Python
{
  "imie": "Anna",
  "wiek": 30,
  "czyAktywna": true,
  "hobby": [
    "czytanie",
    "programowanie",
    "gotowanie"
  ],
  "adres": {
    "ulica": "Główna",
    "numer": 15
  },
  "zamowienia": null
}
```

###2. JSON a Python – jak to działa?

JSON składa się z kilku podstawowych struktur danych, które mają swoje bezpośrednie odpowiedniki w Pythonie:

| JSON | Odpowiednik w Pythonie |
| :--- | :--- |
| object | `dict` |
| array | `list` |
| string | `str` |
| number | `int` / `float` |
| boolean (true/false) | `True` / `False` |
| null | `None` |

Python umie automatycznie konwertować dane między tymi formatami przy użyciu modułu:

```python
import json
```

Biblioteka `json` umożliwia:

*  zamianę obiektów Pythona na tekst JSON (serializacja)
*  zamianę tekstu JSON na obiekty Pythona (deserializacja)

Robi to za pomocą czterech podstawowych funkcji:

* `json.dumps()` – zamienia obiekt Pythona na tekst JSON (string)
* `json.loads()` – zamienia tekst JSON na obiekt Pythona (load string)
* `json.dump()` – zapisuje dane w JSON bezpośrednio do pliku
* `json.load()` – wczytuje dane z pliku JSON

### 3. Przykłady zastosowania JSON

#### 3.1. Konwersja słownika na JSON (najczęstsze zastosowanie)
"""

import json

osoba = {
    "imie": "Anna",
    "wiek": 20,
    "student": True
}

# Używamy dumps() do serializacji (z Python -> JSON tekst)
# indent=4 sprawia, że zapis jest ładnie sformatowany.
tekst_json = json.dumps(osoba, indent=4, separators=(',', '-> '), sort_keys=True)
print(tekst_json)
print("Typ zmiennej tekst_json:", type(tekst_json))

"""#### 3.2. Zamiana listy na JSON"""

import json

"""
kolory = {"Shades of red":
          ["scarlet", "ruby", "rose"],
          "Shades of green":
          ["emerald", "olive", "mint"],
          "Shades of blue":
          ["navy", "azure", "cobalt"],
}
"""
kolory = ["red", "blue", "green", "yellow"]
print(kolory)
kolory_json = json.dumps(kolory, indent=4)
print(kolory_json)
print(type(kolory_json))

"""#### 3.3. JSON z liczbą, tekstem i wartościami logicznymi

Warto zauważyć, że Pythonowy `None` staje się JSON-owym `null`.
"""

import json
print("Liczba całkowita:", json.dumps(42))
print("Liczba zmiennoprzecinkowa:", json.dumps(3.14))
print("Tekst:", json.dumps("Hello"))
print("Wartość logiczna:", json.dumps(True))
print("Brak wartości (None -> null):", json.dumps(None))

"""### 4. Praca z plikami JSON

JSON najczęściej używa się nie w konsoli, ale do zapisu i odczytu danych w plikach. Tutaj używamy funkcji `dump()` i `load()`.

#### 4.1. Zapis danych do pliku JSON
"""

import json

biblioteka = {
    "nazwa": "Biblioteka szkolna",
    "ksiazki": ["Hobbit", "Wiedźmin", "Python 101"],
    "otwarta": True
}

# Używamy dump() do zapisu do otwartego pliku
with open("biblioteka.json", "a") as f:
    json.dump(biblioteka, f, indent=4)

print("Dane zostały zapisane do pliku 'biblioteka.json'. Sprawdź katalog plików po lewej stronie Colaba.")

"""#### 4.2. Odczyt danych z pliku JSON"""

import json

# Używamy load() do odczytu z otwartego pliku
with open("biblioteka.json", "r") as f:
    dane = json.load(f)

print("Wczytane dane:", dane)
print("Typ wczytanych danych:", type(dane))

# Po odczytaniu otrzymujemy normalny słownik - można go modyfikować jak każdy inny obiekt Pythona.
print("Pierwsza książka:", dane["ksiazki"][0])

"""### 5. Wykorzystanie JSON w praktyce

To właśnie w takim formacie (poniżej) komunikują się aplikacje mobilne i strony internetowe z serwerami (API).
"""

import json

# Przykładowa odpowiedź w formie tekstu JSON (symulacja z API pogodowego):
odpowiedz_api = """{
    "status": "ok",
    "temperatura": 18,
    "prognoza": ["slonecznie", "deszcz", "wiatr"]
}"""

print(type(odpowiedz_api))
# Używamy loads() do deserializacji (z tekstu JSON -> Python dict)
dane_pogodowe = json.loads(odpowiedz_api)
print(type(dane_pogodowe))

print("Temperatura:", dane_pogodowe["temperatura"]) # 18
print("Jutro będzie:", dane_pogodowe["prognoza"][1]) # deszcz

"""### 6. JSON a klasy – zapis obiektów

JSON nie potrafi zapisywać obiektów klasy bezpośrednio. Aby to obejść, przed serializacją zamieniamy obiekt na słownik (który jest natywnie obsługiwany przez JSON).
"""

import json

class Osoba:
    def __init__(self, imie, wiek):
        self.imie = imie
        self.wiek = wiek

o = Osoba("Jan", 30)

# Ręczna konwersja obiektu na słownik
dane = {
    "imie": o.imie,
    "wiek": o.wiek
}

print(json.dumps(dane, indent=4))
print(dane)


# Właśnie tak zapisuje się dane np. w projektach typu „biblioteka”, „książka telefoniczna”, „system ocen”.

"""### 7. Zadania

Zadania są uporządkowane od prostych do bardzo zaawansowanych. Uruchom poniższe komórki i spróbuj rozwiązać zadania!

#### 7.1. Zamień słownik na dane JSON

Dany jest słownik:

```python
dane_ucznia = {"imie": "Tomek", "wiek": 19, "klasa": "4TI"}
```
Wypisz go jako czytelny JSON (użyj `indent`).
"""

import json

dane_ucznia = {"imie": "Tomek", "wiek": 19, "klasa": "4TI"}

# Twój kod tutaj (użyj json.dumps i print):

"""#### 7.2. Zapisz listę liczb do pliku JSON

Lista:

```python
lista_liczb = [5, 12, 7, 9]
```
Zapisz ją do pliku o nazwie `lista.json` (użyj `json.dump`). Następnie wczytaj tę listę z pliku do nowej listy: `nowa_lista`, wyświetl ją i oblicz z niej średnią.
"""

import json

lista_liczb = [5, 12, 7, 9]


# Twój kod tutaj (użyj open() oraz json.dump do zapisu pliku, następnie ponownie otwórz plik do odczytu i użyj json.load do pobrania nowej listy):

"""#### 7.3. Odczytaj JSON z pliku

Najpierw uruchom komórkę tworzącą plik `kolory.json`. Następnie w komórce z zadaniem wczytaj dane i wypisz kolory linia po linii.
"""

# Krok 1: Tworzenie pliku (nie modyfikuj)
import json
with open("kolory.json", "w") as f:
    json.dump(["red", "green", "blue", "yellow"], f)

print("Plik kolory.json został utworzony.")

import json

# Krok 2: Odczyt danych z pliku (Twój kod tutaj):


# Wskazówka: po wczytaniu otrzymasz listę. Użyj pętli for do wypisania elementów.

"""#### 7.4. Dane uczniów i obliczanie średniej

Zapisz poniższą listę słowników do pliku `oceny.json`, a następnie wczytaj ją z powrotem i oblicz średnią ocen dla wszystkich uczniów.
"""

import json

lista_uczniow = [
    {"imie": "Asia", "ocena": 5},
    {"imie": "Kuba", "ocena": 3},
    {"imie": "Ola", "ocena": 4}
]

# Krok 1: Zapis listy_uczniow do oceny.json
# ...

# Krok 2: Odczyt danych z oceny.json
# ...

# Krok 3: Obliczenie i wypisanie średniej ocen
# ...

"""#### 7.5. Dane pogodowe i najwyższa temperatura

Wczytaj dane z pliku `pogoda.json` (utworzonego poniżej), a następnie wypisz najwyższą temperaturę odczytaną z listy `"temperatury"`.
"""

# Krok 1: Tworzenie pliku (nie modyfikuj)
import json
dane_pogodowe = {
    "temperatury": [10, 12, 14, 9, 15, 11],
    "wilgotnosc": 80
}
with open("pogoda.json", "w") as f:
    json.dump(dane_pogodowe, f)

print("Plik pogoda.json został utworzony.")

import json

# Krok 2: Wczytaj dane z pogoda.json
# ...

# Krok 3: Wypisz najwyższą temperaturę (pamiętaj, że "temperatury" to lista)
# ...

"""### Zadania trudne

#### 7.6. Łączenie danych z dwóch plików

Poniżej zostały utworzone dwa pliki: `klasaA.json` i `klasaB.json`, każdy zawierający listę uczniów. Połącz te dwie listy w jedną, a następnie zapisz całą listę do nowego pliku `wszyscy.json`.
"""

# Krok 1: Tworzenie plików (nie modyfikuj)
import json

klasa_a = [{"imie": "Piotr", "id": 1}, {"imie": "Ewa", "id": 2}]
klasa_b = [{"imie": "Adam", "id": 3}, {"imie": "Kasia", "id": 4}]

with open("klasaA.json", "w") as f:
    json.dump(klasa_a, f)
with open("klasaB.json", "w") as f:
    json.dump(klasa_b, f)

print("Pliki klasA.json i klasB.json zostały utworzone.")

import json

# Krok 2: Wczytaj dane z klasaA.json i klasaB.json
# ...

# Krok 3: Połącz w jedną listę (np. używając operatora +)
# ...

# Krok 4: Zapis połączonej listy do wszyscy.json
# ...

"""#### 7.7. Projekt: Książka telefoniczna JSON

Napisz program (używając funkcji), który symuluje prostą książkę telefoniczną. Powinien on:

* **Załadować** kontakty z pliku `kontakty.json` przy starcie (jeśli plik nie istnieje, zacząć z pustą listą).
* Umożliwić **dodawanie** kontaktów (imię, telefon).
* Umożliwić **wyświetlanie** listy kontaktów.
* **Zapisywać** aktualny stan kontaktów do `kontakty.json` przed zakończeniem pracy.
"""

import json
import os # moduł do pracy z systemem plików, użyteczny do sprawdzania, czy plik istnieje

PLIK_KONTAKTOW = "kontakty.json"

def zaladuj_kontakty():
    # Sprawdź, czy plik istnieje i wczytaj go. W przeciwnym razie zwróć pustą listę.
    # ...
    pass

def zapisz_kontakty(lista_kontaktow):
    # Zapisz listę kontaktów do pliku JSON.
    # ...
    pass

def dodaj_kontakt(lista_kontaktow, imie, telefon):
    # Dodaj nowy słownik do listy_kontaktow
    # ...
    pass

def wyswietl_kontakty(lista_kontaktow):
    # Wypisz listę w czytelny sposób
    # ...
    pass

# Pętla główna programu (przykładowe użycie):
kontakty = zaladuj_kontakty()

dodaj_kontakt(kontakty, "Alicja", "111-222-333")
dodaj_kontakt(kontakty, "Bartosz", "444-555-666")

wyswietl_kontakty(kontakty)

zapisz_kontakty(kontakty)
print("Kontakty zapisane do", PLIK_KONTAKTOW)