# -*- coding: utf-8 -*-
"""Lekcja_8-operacje na plikach.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kql21grusPTdCciUYxLbE3Eh5PSKMQFJ

## **Lekcja 8 — Operacje na plikach (czytanie, zapisywanie, dopisywanie)**

### 1. Wprowadzenie

W Pythonie możemy pracować z plikami zapisanymi na komputerze. Najczęściej używamy funkcji:

### `open(nazwa_pliku, tryb)`

Tryby pracy z plikiem:

* `"r"` — odczyt (read)
* `"w"` — zapis (write) – **nadpisuje całą zawartość pliku**
* `"a"` — dopisywanie na końcu pliku (append)
* `"r+"` — odczyt i zapis
* `"wb" / "rb"` — zapis/odczyt w trybie binarnym (np. dla obrazów)

Po zakończeniu pracy z plikiem **zawsze zamykamy go** metodą `.close()`,
lub — bezpieczniej — używamy konstrukcji `with`, która zamyka plik automatycznie.

---

### 2. Przykłady
Poniższe przykłady zakładają, że w katalogu, w którym uruchamiasz notatnik, znajduje się plik `dane.txt` z następującą zawartością:

```
Pierwsza linia
Druga linia
```

#### **Przykład 1 — zapis do pliku („w”)**
Tworzy lub nadpisuje plik `dane_nowe.txt`.
"""

# Tryb "w" (write) nadpisuje plik!
with open("dane_nowe.txt", "w") as plik:
    plik.write("Pierwsza linia nowego pliku\n")
    plik.write("Druga linia nowego pliku\n")

print("Zapis zakończony. Sprawdź zawartość pliku dane_nowe.txt")

"""#### **Przykład 2 — dopisywanie do pliku („a”)**
Dopisywanie do wcześniej utworzonego pliku `dane_nowe.txt`.
"""

# Tryb "a" (append) dopisuje na koniec pliku
with open("dane_nowe.txt", "a") as plik:
    plik.write("Dopisuję kolejną linijkę na końcu\n")

print("Dopisanie zakończone. Sprawdź plik dane_nowe.txt ponownie.")

"""#### **Przykład 3 — odczyt całego pliku (`.read()`)**
Odczytujemy całą zawartość pliku `dane.txt` do jednej zmiennej typu string.
"""

# Tryb "r" (read)
with open("dane.txt", "r") as plik:
    tekst = plik.read()
    print("--- Zawartość pliku ---")
    print(tekst)
    print("----------------------")

"""#### **Przykład 4 — odczyt linia po linii (iteracja)**
Najczęściej używana technika. Pętla `for` automatycznie iteruje po liniach pliku.
"""

with open("dane.txt", "r") as plik:
    print("Odczyt linia po linii:")
    for linia in plik:
        # .strip() usuwa białe znaki, w tym znak nowej linii (\n)
        print("->", linia.strip())

"""#### **Przykład 5 — odczyt do listy (`.readlines()`)**
Funkcja `.readlines()` odczytuje wszystkie linie i zwraca je jako listę ciągów tekstowych. Każdy element listy zawiera znak końca linii (`\n`).
"""

with open("dane.txt", "r") as plik:
    linie = plik.readlines()

print("Lista linii (z \\n):")
print(linie)

"""#### **Przykład 6 — zapis listy do pliku (`.writelines()`)**
Funkcja `.writelines()` przyjmuje listę ciągów tekstowych. Ważne: musimy ręcznie dodać znak nowej linii do każdego elementu, jeśli chcemy, by były w osobnych wierszach.
"""

lista = ["Ala", "ma", "kota", "i", "psa"]

# 1. Przygotowanie listy z nowymi liniami
linie_do_zapisu = [slowo + "\n" for slowo in lista]

with open("lista_wynikowa.txt", "w") as plik:
    plik.writelines(linie_do_zapisu)

print("Zapis listy zakończony. Sprawdź plik lista_wynikowa.txt")

"""---

### 3. Zadania dla uczniów

Użyj następujące pliki tekstowe: `liczby.txt`, `tekst.txt`, `log.txt`, `oceny.txt`.

#### **Zadanie 1**

Napisz program, który:

1. Poprosi użytkownika o wpisanie swojego ulubionego imienia lub kilku imion.
2. Zapisze to imię **na końcu** pliku `ulubione_imiona.txt` każde w odzielnej linii. Jeśli plik nie istnieje, powinien zostać utworzony.
3. Wyświetli komunikat, że imię zostało dodane.
"""

# Prośba o imię
imie = input("Podaj swoje ulubione imiona: ").split()

# Tryb "a" (append) - dopisuje na końcu pliku
# Dodajemy znak nowej linii, aby każde imię było w osobnym wierszu
with open("ulubione_imiona.txt", "a") as plik:
    for linia in imie:
        plik.write(linia + "\n")

print(f"Imię '{imie}' zostało dodane do pliku ulubione_imiona.txt.")

"""#### **Zadanie 2**

Wczytaj plik `liczby.txt`, w którym każda linia zawiera jedną liczbę całkowitą.
Policz sumę oraz średnią wszystkich liczb i wyświetl wynik w konsoli.
"""

suma = 0
ile = 0

try:
    # Wczytanie pliku w trybie "r"
    with open("liczby.txt", "r") as plik:
        for linia in plik:
            # Usuwamy białe znaki (w tym \n) i konwertujemy na liczbę całkowitą
            liczba = int(linia)
            suma += liczba
            ile += 1

    print(f"Suma wszystkich liczb w pliku liczby.txt wynosi: {suma}")
    print(f"Średnia wszystkich liczb w pliku liczby.txt wynosi: {suma/ile}")
except FileNotFoundError:
    print("Błąd: Plik liczby.txt nie został znaleziony.")
except ValueError:
    print("Błąd: Jedna z linii w pliku nie jest poprawną liczbą.")

"""#### **Zadanie 3**

W pliku `tekst.txt` znajduje się długi tekst.
Policz **całkowitą liczbę słów** w tym pliku i wyświetl wynik.

Wskazówka: Jak oddzielić słowa w tekście?
"""

liczba_slow = 0
liczba_literki = 0
try:
    with open("tekst.txt", "r") as plik:
        # 1. Wczytujemy cały tekst do jednej zmiennej
        tekst = plik.read()
        print(tekst)

        # 2. Usuwamy znaki nowej linii, aby wszystko było w jednym ciągu
        tekst = tekst.replace('\n', ' ').replace('.','').replace(',','')

        # 3. Dzielimy tekst na listę słów, używając spacji jako separatora
        # Metoda .split() bez argumentów automatycznie obsługuje wielokrotne spacje
        slowa = tekst.split()
        print(slowa)
        for slowo in slowa:
            if 'o' in slowo or 'O' in slowo:
                liczba_literki += 1

        # 4. Liczymy elementy w liście
        liczba_slow = len(slowa)

    print(f"Całkowita liczba słów w pliku tekst.txt to: {liczba_slow}")
    print(liczba_literki)

except FileNotFoundError:
    print("Błąd: Plik tekst.txt nie został znaleziony.")

"""#### **Zadanie 4**

Utwórz program, który:

1. Wczyta wszystkie linie pliku `log.txt`.
2. Znajdzie linie zawierające słowo kluczowe `"ERROR"`.
3. Zapisze te linie do nowego pliku o nazwie `bledy.txt`.
"""

try:
    # 1. Wczytujemy plik log.txt
    with open("log.txt", "r") as plik_wejsciowy:
        wszystkie_linie = plik_wejsciowy.readlines()
    linie_bledow = []
    # 2. Znajdujemy linie zawierające słowo "ERROR"
    for linia in wszystkie_linie:
        if "ERROR" in linia:
            linie_bledow.append(linia)
    # 3. Zapisujemy linie błędów do pliku bledy.txt
    # Używamy writelines, które zapisuje całą listę
    with open("bledy.txt", "w") as plik_wyjsciowy:
        plik_wyjsciowy.writelines(linie_bledow)
    print(f"Znaleziono {len(linie_bledow)} linii z błędami. Zapisano je do pliku bledy.txt.")

except FileNotFoundError:
    print("Błąd: Plik log.txt nie został znaleziony.")

"""#### **Zadanie 5 (trudne)**

Masz plik `oceny.txt`, w którym każda linia ma format: `imie,ocena` (np. `Anna,5`).

Napisz program, który:

* Wczyta wszystkie oceny (ignorując imiona).
* Obliczy **średnią arytmetyczną** ocen.
* Zapisze wynik średniej (np. `4.16`) do pliku `srednia.txt`.
"""

sum_ocen = 0
liczba_ocen = 0

try:
    with open("oceny.txt", "r") as plik:
        for linia in plik:
            # Usuwamy białe znaki i dzielimy linię na listę (separator - ',')
            czesci = linia.strip().split(',')

            if len(czesci) == 2:
                # Część na indeksie 1 to ocena (ciąg tekstowy)
                ocena_str = czesci[1]

                # Konwersja na liczbę całkowitą
                ocena = int(ocena_str)

                sum_ocen += ocena
                liczba_ocen += 1

    if liczba_ocen > 0:
        srednia = sum_ocen / liczba_ocen

        # Zapis średniej do pliku srednia.txt
        with open("srednia.txt", "w") as plik_srednia:
            # Formatujemy średnią do 2 miejsc po przecinku
            plik_srednia.write(f"{srednia:.2f}")

        print(f"Średnia ocen wynosi: {srednia:.2f}. Wynik zapisano do srednia.txt.")
    else:
        print("Brak ocen w pliku do obliczenia średniej.")

except FileNotFoundError:
    print("Błąd: Plik oceny.txt nie został znaleziony.")
except ValueError:
    print("Błąd: W pliku znajduje się nieprawidłowy format oceny (nie jest liczbą).")

"""#### **Zadanie 6 (trudne++)**

Stwórz funkcję, która wczyta plik `tekst.txt` i zastąpi wszystkie polskie znaki diakrytyczne (np. ą, ć, ę, ś, ż, ź) ich prostymi odpowiednikami (a, c, e, s, z, z).
Zapisz zmieniony tekst do nowego pliku `tekst_bez_diakrytykow.txt`.

Wskazówka: Utwórz słownik mapujący polskie litery na ich proste odpowiedniki.
"""

def usun_diakrytyki(tekst_wejsciowy):
    """Zamienia polskie znaki diakrytyczne na ich proste odpowiedniki."""

    # Słownik mapujący znaki
    mapowanie = {
        'ą': 'a', 'ć': 'c', 'ę': 'e', 'ł': 'l', 'ń': 'n',
        'ó': 'o', 'ś': 's', 'ż': 'z', 'ź': 'z',
        'Ą': 'A', 'Ć': 'C', 'Ę': 'E', 'Ł': 'L', 'Ń': 'N',
        'Ó': 'O', 'Ś': 'S', 'Ż': 'Z', 'Ź': 'Z',
    }

    tekst_wyjsciowy = tekst_wejsciowy

    # Iterujemy po słowniku i dokonujemy zamiany
    for polski_znak, prosty_znak in mapowanie.items():
        tekst_wyjsciowy = tekst_wyjsciowy.replace(polski_znak, prosty_znak)

    return tekst_wyjsciowy

try:
    # 1. Wczytanie zawartości pliku
    with open("tekst.txt", "r", encoding="utf-8") as plik_do_zmiany:
        zawartosc_pliku = plik_do_zmiany.read()

    # 2. Przetwarzanie tekstu
    tekst_bez_diakrytykow = usun_diakrytyki(zawartosc_pliku)

    # 3. Zapis do nowego pliku
    with open("tekst_bez_diakrytykow.txt", "w", encoding="utf-8") as plik_wynikowy:
        plik_wynikowy.write(tekst_bez_diakrytykow)

    print("Tekst został przetworzony i zapisany do pliku tekst_bez_diakrytykow.txt.")
    print("Oto pierwsza linia przetworzonego tekstu:")
    print(tekst_bez_diakrytykow.split('\n')[0])

except FileNotFoundError:
    print("Błąd: Plik tekst.txt nie został znaleziony.")

